<a href="https://colab.research.google.com/github/EricFalcao/Analise-de-Dados/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.25.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.29)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26771 sha256=191a7583e46ec267a8bd28787bfc2ab7d9ec4bebcc684b2c5576ad2523b32990
  Stored in directory: /root/.cache/pip/wheels/e9/bc/3a/8434bdcccf5779e72894a9b24fecbdcaf97940607eaf4bcdf9
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [4]:
import pandas as pd

In [5]:
import pandasql as ps

### Lendo as bases de dados

In [6]:
dim_cargo = pd.read_csv('https://raw.githubusercontent.com/rgaguiar/banco_lotacao/main/cargo.csv')
dim_departamento = pd.read_csv('https://raw.githubusercontent.com/rgaguiar/banco_lotacao/main/departamento.csv')
dim_funcionario = pd.read_csv('https://raw.githubusercontent.com/rgaguiar/banco_lotacao/main/funcionario.csv')
fato_lotacao = pd.read_csv('https://raw.githubusercontent.com/rgaguiar/banco_lotacao/main/lotacao.csv')

In [16]:
print('tabela dim_cargo')
display(dim_cargo.head(2))
print('dim_departamento')
display(dim_departamento.head(2))

tabela dim_cargo

   id               nome
0   1  Analista de Dados
1   2        Programador

dim_departamento

   id                      nome
0   1  Tecnologia da Informação
1   2            Administrativo

#Aplicando instruções em SQL

Quantos registros possui o banco lotação?

In [11]:
query = """
select
'Numero de Registros'as Nome,
count(*) as quantidade
from fato_lotacao
"""
ps.sqldf(query, locals())

                  Nome  quantidade
0  Numero de Registros          13

O banco possui 13 registros.

Departamento com a maior folha salarial?

In [12]:
display(dim_departamento.head(2))
display(fato_lotacao.head(2))

   id                      nome
0   1  Tecnologia da Informação
1   2            Administrativo

   id  id_funcionario  id_departamento  id_cargo  salario    cadastro  ativo
0   1               1                1         1   9000.0  2022-09-01   True
1   2               2                2         2   7500.0  2022-09-02   True

In [7]:
query = """
select
dp.nome as departamento
sum(lt.salario) as maior_salario_dp
from fato_lotacao as lt
inner join dim_departamento as dp on dp.id=id.id_departamento
group by
dp.nome

"""
ps.sqldf(query, locals())

PandaSQLException: (sqlite3.OperationalError) near "sum": syntax error
[SQL:
select
dp.nome as departamento
sum(lt.salario) as maior_salario_dp
from fato_lotacao as lt
inner join dim_departamento as dp on dp.id=id.id_departamento
group by
dp.nome

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Cargo melhor remjunerado(em media)?

In [9]:
query = """
select
dg.nome as cargo
avg(lt.salario) as media_salario
from fato_lotacao as lt
inner join dim_cargo as cg on cg.id=lt.id_cargo
group by
cg.nome
order by media_salario desc
"""
ps.sqldf(query, locals())

PandaSQLException: (sqlite3.OperationalError) near "avg": syntax error
[SQL:
select
dg.nome as cargo
avg(lt.salario) as media_salario
from fato_lotacao as lt
inner join dim_cargo as cg on cg.id=lt.id_cargo
group by
cg.nome
order by media_salario desc
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)